### ISSUE TITLE
Pass Array to DSC

### ISSUE THREAD

**Issue by chughesvf** [puppetlabs/puppetlabs-dsc_lite#54]
This may not actually be an issue but I have made few attempts to pass a string array to a resource property with failures that "Convert property from type 'STRING' to type 'STRING[]' failed". Any suggestions? I am thinking dsc_type might work. Thank you in advance!

**Comment by chughesvf** [comment]
there is a similar discussion that was had in the puppetlabs-dsc module:

https://tickets.puppetlabs.com/browse/MODULES-2205

**Comment by Iristyle** [comment]
Hi @chughesvf - We do have code in place for properly formatting an Array when passing values to PowerShell at https://github.com/puppetlabs/puppetlabs-dsc_lite/blob/26c31b4a9a677cf25770663bdbf9258c0830f8a6/lib/puppet_x/puppetlabs/dsc_lite/powershell_hash_formatter.rb#L16-L17.

How are you supplying the values in the manifest? You should always be using Puppet array syntax like `foo => ['bar']` or `foo => ['bar', 'baz']` (even when there is only one value in the array).

What version of Puppet are you using? Can you supply the output from a call to `puppet apply` with `--trace --debug --verbose` also specified?

Thanks

**Comment by jpogran** [comment]
Hi @chughesvf you haven't responded in awhile, so I'm going to close out this issue.

Puppet is closing down the issues tab in this repo. If you have any issues in the future please open a ticket in our JIRA ticket [tracker](https://tickets.puppetlabs.com).
