### ISSUE TITLE
Using sensitive in MSFT_Credential type

### ISSUE THREAD

**Issue by bsmienk** [puppetlabs/puppetlabs-dsc_lite#82]
Hello,

I have just upgraded dsc_lite from 0.2.0 to 1.0.0 and saw in the readme/changelog that I can use the Sensitive function for credentials that are being converted to 'MSFT_Credential'.

I have tried applying this, but it does not seem to work.
```
dsc { 'cMisc_LocalGroup_Administrators' :
  resource_name => 'cMisc_LocalGroup',
  module        => 'cMisc',
  properties    => {
    ensure               => 'present',
    group                => 'Administrators',
    members              => $local_admins,
    psdscrunascredential => {
      dsc_type       => 'MSFT_Credential',
      dsc_properties => {
        user     => 'username',
        password => Sensitive('Password!'),
      },
    },
  },
}
```
A puppet run in debug mode will show the following:

```
$invokeParams = @{
Name       = 'cMisc_LocalGroup'
ModuleName = 'cMisc'
Method     = 'test'
Property   = @{
'ensure' = 'present';
'group' = 'Administrators';
'members' = @('user1', 'user2');
'psdscrunascredential' = ([PSCustomObject]@{
'user' = 'username';
'password' = 'Sensitive [value redacted]'
} | new-pscredential)
}
}
```
So far it seems to be working (the password is redacted).
However, an error occures directly after:

`Error: /Stage[main]/Core::Profile::Cmc::Base/Dsc[cMisc_LocalGroup_Administrators]: Could not evaluate: The user name or password is incorrect`

Edit: I have tried applying the same manifest but without using the Sensitive function, and this fixed the problem (but showed the password in debug mode).

Extra information: 

Powershell version
```
Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
Puppet agent version: 1.10.12
Puppet version: 4.10.11
Windows version: Windows 2012 R2

**Comment by jpogran** [comment]
Hi @bsmienk there was a recent fix to handling Sensitive values with Puppet 6 and Puppet 5 in https://tickets.puppetlabs.com/browse/MODULES-8175. We are releasing the module with that fix this week. Please check that release to see if it fixes the issue you describe here.

Puppet is closing down the issues tab in this repo. If you have any issues with regards to the above please open a ticket in our JIRA ticket [tracker](https://tickets.puppetlabs.com).
