### ISSUE TITLE
Environment isolation

### ISSUE THREAD

**Issue by bsmienk** [puppetlabs/puppetlabs-dsc_lite#83]
I have just upgraded from dsc_lite 0.2.0 to 1.0.0 in my own environment.
Because the parameter names have changed (for example, dsc_resource_module is now resource_module) I had to change my manifests to keep it working. 

The first thing I noticed is that, even though I had changed the manifests to use the correct parameter names, a puppet run still failed because 'resource_module' was not recognized as a parameter. I have seen this before in another module, and knew that I just had to restart the puppetserver process on the puppetmaster.

I did that, and it worked fine after that.

The problem is that another user, in another environment that still uses 0.2.0 now started to get errors in puppet runs because 'dsc_resource_module' was now now longer being recognized as a parameter.

I have been searching for a solution to this issue and found this:
https://puppet.com/docs/puppet/5.3/environment_isolation.html

Is this something that can be fixed in the module or am I supposed to generate the types as described in the link above?

**Comment by bsmienk** [comment]
I have created a ticket at puppetlabs: https://tickets.puppetlabs.com/browse/MODULES-7741

**Comment by jpogran** [comment]
Hi @bsmienk, Puppet is closing down the issues tab in this repo, so I'm closing this issue here. I'll add the ticket you created to our triage and tag it so it will be looked at in the next meeting.
